# Generated by Django 2.1.2 on 2018-11-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(default='shohei', max_length=10),
        ),
    ]
